### PR TITLE
Move some README docs into doc comments

### PR DESCRIPTION
**Pull request by bjz**

### CODE REVIEW

**Comment by Cifram** [comment]
Can you expand the comments on the brownian builder functions to describe what persistence and lacunarity actually are? Since that bit of explanation is removed from the README.

**Comment by bjz** [comment]
Oh, I thought having them on the fields was enough... I will add them to the builder methods though.

**Comment by bjz** [comment]
Done!

**Comment by Cifram** [comment]
Oh, I hadn't noticed that it was on the fields... Still, good to have it in both places.

**Comment by bjz** [comment]
cc #22

**Pull request merged**
